# -*- coding: utf-8 -*-
"""manipulasi string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11hX_CAEbKsr4IALwOfdz3aGi1lGuNcP6

**String**
"""

nama = 'Fery Ilham'
asal = "Rajabasa"

print(nama)

print(asal)

"""**manipulasi string**"""

print(nama, asal)

print("halo, nama saya")

print("halo, nama saya", nama, "asal saya dari", asal)

data_lengkap = nama + asal

print(data_lengkap)

"""**String + non string**"""

asal_kota = "Bandar Lampung"
kode_pos = 35144

asal_kota_kode_pos = asal_kota + str(kode_pos)

print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3

print(asal_kota * 3)

print('Dia berkata:"Pergilah!"')

print("Aku menimpali: \"Apakah kau ingin aku angkat kaki'?!\"")

print ("\\(^_^) / (\\-_-/)")