# -*- coding: utf-8 -*-
"""String3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bYwDT6eak_gc6tWq3dqoZ84mFOQV70Gq

**Format specifiers**
"""

template = "Halo, saya %s dari %s"
print(template % ("Lendis Fabri", "Indonesia"))

"""**Fungsi format()**

"""

template = "Halo, saya {nama} dari {asal}"
template_2 = "Saya suka makan {} dan minum {}"
print(template.format(nama="Lendis Fabri", asal="Indonesia"))
print(template_2.format("nasi goreng", "air putih"))

"""**String interpolation / F-string**

"""

nama = "Lendis Fabri"
asal = "Indonesia"

print(f"Perkenalkan saya {nama} dari {asal}")

"""**Memecah string menjadi list dan sebaliknya**

"""

alamat = "Surabaya, Jawa Timur, Indonesia"

print(alamat.split())
print(alamat.split(","))
print(alamat.split(", "))

print("😍".join(["aku", "suka", "python"]))
print("😘".join(alamat.split(", ")))

"""**Mengubah string menjadi upper case**

"""

print("halo selamat pagi!".upper())
print("halo selamat siang!".upper())

salam = "السلام علیکم"

print(salam)

print(salam.upper())

"""**Mengubah string menjadi lower case**"""

print("APA KABAR?".lower())
print("LAGI DIMANA?".lower())

"""**Mengubah string menjadi title case**"""

print("daun tidak pernah membenci angin".title())
print("LASKAR PELANGI".title())

"""**Mengubah string menjadi reverse case**"""

print("Indonesia Adalah Negara Kepulauan".swapcase())
print("aku cInta NeGeRIKu".swapcase())

"""**mencari kata pada string**"""

angka = "12345"

print("Index angka 3:", angka.find("3"))
print("Index angka 45:", angka.find("45"))
print("Index angka 35:", angka.find("35"))

"""**me replace kata pada string**"""

ibu_kota = "Jakarta"

print(ibu_kota.replace("a", "i"))
print(ibu_kota.replace("kar", "ta"))
print(ibu_kota.replace("a", ""))

"""**menghitung jumlah kata pada string**"""

paragraf = "Gortory ini telah ditemukan sebuah meteor di suatu sungai"

x = paragraf.count("di")

print("kata 'di' muncul sebanyak", x, "kali")