# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JekZMpZQhzD8R4gEx-t_lHfhwQtTfpBU

**Operasi in Pada String**
"""

informasi = 'Bahwasannya besok libur sampai minggu depan'

print('sublime text' in informasi)
print('notepad++' in informasi)

"""**Memotong String**"""

nama = 'Fery Ilham'

print(nama [9])
print(nama [8])
print(nama [7])
print(nama [6])
print(nama [5])

"""**Slicing String**"""

nama_npm = 'Fery Ilham_2451012011'

print(nama_npm [0:4])
print(nama_npm [4:10])
print(nama_npm [11:16])
print(nama_npm [:-11])
print(nama_npm [-10:])

"""**Menghitung Panjang String**"""

print(len('Universitas Lampung'))
print(len('Bisnis Digital'))

"""**Memeriksa Karakter Awal String**"""

no_npm_1 = '2444444444'
no_npm_2 = '2451333234'
no_npm_3 = '2315834958'

masuk_2024 = '24'

print(no_npm_1.startswith(masuk_2024))
print(no_npm_2.startswith(masuk_2024))
print(no_npm_3.startswith(masuk_2024))

"""**Memeriksa Karakter Akhir String**"""

ptn_asli_tidak_1 = 'unila'
ptn_asli_tidak_2 = 'ulani'

print(ptn_asli_tidak_1.endswith('unila'))
print(ptn_asli_tidak_2.endswith('unila'))