# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10gYtWUT6Hp7RXl39Sj9cowQ_4nup8JBI

**MEMERIKSA JENIS TIPE DATA**
"""

nama = 'peri'
usia = 100
lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

"""**KONVERSI TIPE DATA**"""

usia =input('100')
print(type(usia))

"""**KONVERSI TIPE DATA IMPLISIT**"""

a = 70/2
print(type(a))

"""**KONVERSI TIPE DATA SECARA NUMERIK**"""

panjang = int(input('masukkan panjang: '))
lebar = float(input('masukkan lebar '))
print('Luas =', panjang * lebar)

"""**KONVERSI NUMERIK KE STRING**"""

xnama ="peri"
tahun_lahir = 1945
print(nama + ' lahir ditahun ini ' + str(tahun_lahir))