# -*- coding: utf-8 -*-
"""UTS Compro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13o4Lc2GgwTPhE13vXNNIvrsVHEDwMJyg

*   Nama: Fery Ilham
*   NPM: 2451012011


*   Kelompok: 7
"""

#Data mentah
#Pertama, kita membuat fungsi raw_log yang berfungsi untuk menyimpan data mentah
raw_log = "ID:001#NAMA:kopi susu gula aren#QTY:3#PRICE:18000;ID:002#NAMA:COFFEE LATTE#QTY:1#PRICE:25000"

#Data Splitting (Double Split manual)
#selanjut nya kita membuat funngsi yang bernama pisah_rawlog yang berfungsi untuk menyimpan data mentah tadi yang sudah dilakukan pemisahan atau split simbol ";"
pisah_rawlog = raw_log.split(";")

#Memecah transaksi pertama
#selanjut nya setelah dilakukan split simbol ";", kita akan mendapatkan 2 buah data transaksi yaitu [0] dan [1], setelah itu kita melakukan split lagi untuk memisahkan simbol "#" pada 2 buah data tersebut
transaksi_satu = pisah_rawlog[0].split("#")
#Memecah transaksi kedua
transaksi_dua = pisah_rawlog[1].split("#")

#Advanced Cleaning (replace & strip) & Transformation (title)
#selanjutnya kita melakukan advance cleaning yaitu membuang label teks "NAMA:", "QTY", dan "PRICE" menggunakan replace, dan strip untuk menghapus spasi nya, dan juga di sini kita langsung mengubah nama menu pada data 1 dan data 2 menjadi title
# Transaksi 1
nama_ts1  = transaksi_satu[1].replace("NAMA:", "").strip().title()
kuantitas_ts1   = int(transaksi_satu[2].replace("QTY:", "").strip())
harga_ts1 = int(transaksi_satu[3].replace("PRICE:", "").strip())

# Transaksi 2
nama_ts2  = transaksi_dua[1].replace("NAMA:", "").strip().title()
kuantitas_ts2  = int(transaksi_dua[2].replace("QTY:", "").strip())
harga_ts2 = int(transaksi_dua[3].replace("PRICE:", "").strip())

#Perhitungan Aritmatika
#selanjutnya adalah perhitungan, disini kita membuat fungsi total untuk menampung perhitungan (kuantitas x harga) pada data 1 dan 2, setelah di dapat perhitungan nya kita membuat fungsi harga total untuk menghitung dari total harga 1 dand 2
total_ts1 = kuantitas_ts1 * harga_ts1
total_ts2 = kuantitas_ts2 * harga_ts2
harga_total = total_ts1 + total_ts2

#Output Laporan (F-String Alignment)
#selanjutnya adalah code untuk menampilkan data yang sudah di susun, yaitu menggunakan print.
print("=" * 50)
print("         LAPORAN HARIAN KEDAI SOU SPACE")
print("=" * 50)
print(f"{'MENU':<24} {'QTY':<6} {'HARGA':<9} {'SUBTOTAL'}")
print("-" * 50)
print(f"{nama_ts1:<25} {kuantitas_ts1:<5} {harga_ts1:<10} {total_ts1}")
print(f"{nama_ts2:<25} {kuantitas_ts2:<5} {harga_ts2:<10} {total_ts2}")
print("-" *50 )
print(f"TOTAL PENDAPATAN HARI INI: Rp {harga_total}")
print("=" * 50)